# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  configuration: release
  platform: "any cpu"
  solutionPath: "./VideoDatabase.sln"
  azureServiceConnection: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'

pool:
  vmImage: windows-latest



steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    KeyVaultName: musicvideobuilder
    SecretsFilter: 'SqlAdministratorLogin,SqlAdministratorPassword,SqlLoginMusicVideoBuilderApplicationPassword'
    RunAsPreJob: false

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: $(solutionPath)
    platform: $(platform)
    configuration: $(configuration)
    clean: true

- task: SqlAzureDacpacDeployment@1
  displayName: Execute Azure SQL Dacpac
  inputs:
    azureSubscription: $(azureServiceConnection)
    AuthenticationType: 'aadAuthenticationIntegrated'
    ServerName: musicvideobuilder.database.windows.net
    DatabaseName: musicvideobuilder
    DacpacFile: '$(Build.SourcesDirectory)/VideoDatabase/bin/$(configuration)/VideoDatabase.dacpac'      
