CREATE TABLE [dbo].[User]
(
	[UserId] INT IDENTITY NOT NULL PRIMARY KEY,
	[ExternalUserId] NVARCHAR(100) NOT NULL UNIQUE,
	[Email] NVARCHAR(255) NOT NULL,
	[DateCreated] DATETIME2 NOT NULL,
	[DateUpdated] DATETIME2 NOT NULL,
)
